server:
  address: 0.0.0.0
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/healthy_db?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
    username: root
    password: root159357
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true

ses:
  lifestyles:
    lifestyle1:
      lifestyleId: 1
      lifestyleName: Activ
    lifestyle2:
      lifestyleId: 2
      lifestyleName: Semiactiv
    lifestyle3:
      lifestyleId: 3
      lifestyleName: Sedentar